version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://itms_user:itms_password@db:5432/itms_db
    depends_on:
      - db
    networks:
      - itms_network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=itms_db
      - POSTGRES_USER=itms_user
      - POSTGRES_PASSWORD=itms_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - itms_network

volumes:
  postgres_data:

networks:
  itms_network:
    driver: bridge