# Generated by Django 4.2.7 on 2025-09-01 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itms_app', '0003_complianceframework_disasterrecoveryplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_image',
            field=models.ImageField(blank=True, help_text='Photo of the asset', null=True, upload_to='assets/'),
        ),
        migrations.AddField(
            model_name='asset',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode number if applicable', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('excellent', '⭐ Excellent'), ('good', '✅ Good'), ('fair', '⚠️ Fair'), ('poor', '❌ Poor'), ('unknown', '❓ Unknown')], default='unknown', help_text='Physical condition of the asset', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual depreciation rate (%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(help_text='Unique identifier for this asset (e.g., ITMS-2024-001)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Person responsible for this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(help_text='Asset category', on_delete=django.db.models.deletion.CASCADE, to='itms_app.category'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(help_text='Physical location of the asset', on_delete=django.db.models.deletion.CASCADE, to='itms_app.location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Manufacturer or brand', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, help_text='Model name/number', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(help_text='Asset name or description', max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes and comments'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original purchase cost', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Date when asset was purchased', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, help_text="Manufacturer's serial number", max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', '🟢 Active'), ('inactive', '🔴 Inactive'), ('maintenance', '🔧 Under Maintenance'), ('retired', '📦 Retired'), ('disposed', '🗑️ Disposed')], default='active', help_text='Current operational status', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Supplier or vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='itms_app.vendor'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='warranty_expiry',
            field=models.DateField(blank=True, help_text='Warranty expiration date', null=True),
        ),
    ]
